### ISSUE TITLE
Release tagging

### ISSUE THREAD

**Issue by sebastic** [jklimke/libcitygml#11]
Since code.google.com is shutting down, and the libcitygml project there has been dead for awhile, are you planning to tag releases here on GitHub?

This looks like the most viable successor of the Google hosted project and I'd like to switch the libcitygml Debian package to use this repo. Having tagged releases makes it much easier to package.

**Comment by jklimke** [comment]
I will start tagging releases if you would like to start using the repo as basis for the debian package build. Since there where some changes applied that would probably break the API compatibility (e.g., using smart pointers) i would start tagging with Release version 1.0.

**Comment by sebastic** [comment]
Thanks for the feedback. The API compatibility doesn't look like a problem since there are no reverse dependencies. For third party applications the SOVERSION just needs a bump to indicate the API breakage.

**Comment by jklimke** [comment]
I just tagged the release. It accidentally did it twice since i did not want to lower our current minor and patch version number from 1.2.1 to 1.0. I will close this issue for now.
