### ISSUE TITLE
I can not compile addressparser.cpp on MSVC 2013

### ISSUE THREAD

**Issue by Jan56** [jklimke/libcitygml#17]
When compiling addressparser.cpp with MSVC 2013, I get the following 2 errors,
-) error C2593: 'operator =' is ambiguous addressparser.cpp	line 52
   That is on the end of statement
                    k_dataElements = {
                        { NodeType::XAL_CountryNameNode, &Address::setCountry },
                        { NodeType::XAL_LocalityNameNode, &Address::setLocality },
                        { NodeType::XAL_ThoroughfareNameNode, &Address::setThoroughfareName },
                        { NodeType::XAL_ThoroughfareNumberNode, &Address::setThoroughfareNumber },
                        { NodeType::XAL_PostalCodeNumberNode, &Address::setPostalCode }
                    };
-) error C2668: 'citygml::`anonymous-namespace'::make_unique' : ambiguous call to overloaded function addressparser.cpp line 85
        m_address = make_unique<Address>(attributes.getCityGMLIDAttribute());

**Comment by jklimke** [comment]
Thank you for the report. We will have a look at it shortly. In case you fix the issue before, please place a pull request so i am able to merge it into this project repo

**Comment by jklimke** [comment]
should be fixed with merged pull request. Thank you for your contribution
