### ISSUE TITLE
std::runtime_error with test datasets

### ISSUE THREAD

**Issue by vindoctor** [jklimke/libcitygml#20]
I did have to make some trivial changes to compile with vs2012.  I can provide this code if you are interested.  CityGML_2.0_Test_Dataset_2012-04-23 is what I'm using, and no matter test data I choose it parses for a while and hits this condition. I was only doing a spot check of this library and it doesn't look like its working out of the box.  Can you test with the citygml test data and see if you are also getting this exception thrown?

   if (!m_boundElement.valid()) {
            // This might happen if an container element that usally contains a child element links to an exting object using XLink an thus
            // uses a combined start/end element: e.g.: <surfaceMember xlink:href="#..."/>
            // For such elements a child parser must only be created if there is no xlink attribute.
            CITYGML_LOG_ERROR(m_logger, "CityGMLElementParser::endElement called on unbound " << elementParserName() << " object for element <" << node << "> at " << getDocumentLocation());
            throw std::runtime_error("CityGMLElementParser::endElement called on unbound CityGMLElementParser object.");
        }

**Comment by jklimke** [comment]
Hi,

where can i find this dataset for testing ? Could you provide a link ? If there are changes you want to commit, please create a fork and create a pull request containing the changes. I appreciate any contribution.

Kind regards,
Jan

**Comment by jklimke** [comment]
it could be that the citygml contained unsupported geometry elements. we added support for OuterCeilingSurface and OuterFloorSurface recently. please try again
