### ISSUE TITLE
Installation of libcitygml

### ISSUE THREAD

**Issue by ivanyuT** [jklimke/libcitygml#21]
Recently, I have tried to create the binary project from the cmake source using CMake 3.4.1 gui form but receive the following message, 

CMake Error at CMakeModules/FindXerces.cmake:109 (MESSAGE):
  Could not find Xerces-C !
Call Stack (most recent call first):
  CMakeLists.txt:134 (FIND_PACKAGE)

Do you have the procedure or document to explain how to convert the cmake source code into the binary project so visual studio can access?

**Comment by jklimke** [comment]
you should download xerces C and set the include and lib dirs accordingly in you gui so that all necessary libs are found
