### ISSUE TITLE
excessive logging

### ISSUE THREAD

**Issue by hurzl** [jklimke/libcitygml#26]
where do I switch off logging in citygml::load?
passing nullptr as logger in the 3rd argument does nothing

**Comment by jklimke** [comment]
if you don't provide a logger to the method it will create a logger using stdout 

I just pushed some changes that initializes the logger with log level error and does not log at levels that have lower importance. 

Loggers can now be initialized with the desried log level (it can also be set during runtime using the new setLogLevel method )

please check out and try if that works for you
