### ISSUE TITLE
CMake Error at CMakeModules/FindXerces.cmake:74 

### ISSUE THREAD

**Issue by shmil** [jklimke/libcitygml#3]
CMake Error at CMakeModules/FindXerces.cmake:74 (MESSAGE):
  Could not find Xerces-C !
when i using camke to configure libcitygml

how can i fix it?
i use libcitygml0.1.3  & citygml2vrml v.0.1.3 &  XERCES 3.1.1
Visual Studio 2010
Windows 7 x64

**Comment by jklimke** [comment]
There where some issues with Visual Studio builds fixed recently. please try again.

**Comment by jklimke** [comment]
Is there still an issue with compiling the code with visual studio ? Otherwise i would close this issue
