### ISSUE TITLE
Fails to build with GCC 7

### ISSUE THREAD

**Issue by sebastic** [jklimke/libcitygml#31]
As reported by Matthias Klose in [Debian Bug #853487](https://bugs.debian.org/853487):
> The package fails to build in a test rebuild on at least amd64 with
> gcc-7/g++-7, but succeeds to build with gcc-6/g++-6. The
> severity of this report may be raised before the buster release.
> There is no need to fix this issue in time for the stretch release.
>
> The full build log can be found at:
> http://people.debian.org/~doko/logs/gcc7-20170126/libcitygml_2.0-3_unstable_gcc7.log
> The last lines of the build log are at the end of this report.
>
> To build with GCC 7, either set CC=gcc-7 CXX=g++-7 explicitly,
> or install the gcc, g++, gfortran, ... packages from experimental.
> 
>   apt-get -t experimental install g++
> 
> Common build failures are new warnings resulting in build failures with
> -Werror turned on, or new/dropped symbols in Debian symbols files.
> For other C/C++ related build failures see the porting guide at
> http://gcc.gnu.org/gcc-7/porting_to.html
>
> ```
> [...]
> cd /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/sources && /usr/bin/c++   -DCITYGML_LIBRARY -DLIBCITYGML_BUILD -DLIBCITYGML_DYNAMIC -DUSE_GDAL -DXERCES_STATIC_LIBRARY -Dcitygml_EXPORTS -I/<<PKGBUILDDIR>>/sources/include -I/usr/include/gdal -I/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/include  -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++11 -fPIC -fPIC   -o CMakeFiles/citygml.dir/src/parser/linestringelementparser.cpp.o -c /<<PKGBUILDDIR>>/sources/src/parser/linestringelementparser.cpp
> [ 90%] Building CXX object sources/CMakeFiles/citygml.dir/src/parser/linearringelementparser.cpp.o
> cd /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/sources && /usr/bin/c++   -DCITYGML_LIBRARY -DLIBCITYGML_BUILD -DLIBCITYGML_DYNAMIC -DUSE_GDAL -DXERCES_STATIC_LIBRARY -Dcitygml_EXPORTS -I/<<PKGBUILDDIR>>/sources/include -I/usr/include/gdal -I/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/include  -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++11 -fPIC -fPIC   -o CMakeFiles/citygml.dir/src/parser/linearringelementparser.cpp.o -c /<<PKGBUILDDIR>>/sources/src/parser/linearringelementparser.cpp
> [ 92%] Building CXX object sources/CMakeFiles/citygml.dir/src/parser/implicitgeometryelementparser.cpp.o
> cd /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/sources && /usr/bin/c++   -DCITYGML_LIBRARY -DLIBCITYGML_BUILD -DLIBCITYGML_DYNAMIC -DUSE_GDAL -DXERCES_STATIC_LIBRARY -Dcitygml_EXPORTS -I/<<PKGBUILDDIR>>/sources/include -I/usr/include/gdal -I/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/include  -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++11 -fPIC -fPIC   -o CMakeFiles/citygml.dir/src/parser/implicitgeometryelementparser.cpp.o -c /<<PKGBUILDDIR>>/sources/src/parser/implicitgeometryelementparser.cpp
> [ 94%] Building CXX object sources/CMakeFiles/citygml.dir/src/parser/addressparser.cpp.o
> cd /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/sources && /usr/bin/c++   -DCITYGML_LIBRARY -DLIBCITYGML_BUILD -DLIBCITYGML_DYNAMIC -DUSE_GDAL -DXERCES_STATIC_LIBRARY -Dcitygml_EXPORTS -I/<<PKGBUILDDIR>>/sources/include -I/usr/include/gdal -I/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/include  -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++11 -fPIC -fPIC   -o CMakeFiles/citygml.dir/src/parser/addressparser.cpp.o -c /<<PKGBUILDDIR>>/sources/src/parser/addressparser.cpp
> In file included from /<<PKGBUILDDIR>>/sources/src/parser/addressparser.cpp:1:0:
> /<<PKGBUILDDIR>>/sources/include/parser/addressparser.h:11:31: error: 'function' in namespace 'std' does not name a template type
>          using Callback = std::function<void(std::unique_ptr<Address>&&)>;
>                                ^~~~~~~~
> In file included from /<<PKGBUILDDIR>>/sources/src/parser/addressparser.cpp:1:0:
> /<<PKGBUILDDIR>>/sources/include/parser/addressparser.h:14:132: error: 'Callback' does not name a type; did you mean 'valloc'?
>          AddressParser(CityGMLDocumentParser& documentParser, CityGMLFactory& factory, std::shared_ptr<CityGMLLogger> logger, const Callback& callback);
>                                                                                                                                     ^~~~~~~~
>                                                                                                                                     valloc
> /<<PKGBUILDDIR>>/sources/include/parser/addressparser.h:28:9: error: 'Callback' does not name a type; did you mean 'valloc'?
>          Callback m_callback;
>          ^~~~~~~~
>          valloc
> /<<PKGBUILDDIR>>/sources/src/parser/addressparser.cpp:61:143: error: 'Callback' does not name a type; did you mean 'valloc'?
>      AddressParser::AddressParser(CityGMLDocumentParser& documentParser, CityGMLFactory& factory, std::shared_ptr<CityGMLLogger> logger, const Callback& callback)
>                                                                                                                                                ^~~~~~~~
>                                                                                                                                                valloc
> /<<PKGBUILDDIR>>/sources/src/parser/addressparser.cpp: In constructor 'citygml::AddressParser::AddressParser(citygml::CityGMLDocumentParser&, citygml::CityGMLFactory&, std::shared_ptr<citygml::CityGMLLogger>, const int&)':
> /<<PKGBUILDDIR>>/sources/src/parser/addressparser.cpp:63:7: error: class 'citygml::AddressParser' does not have any field named 'm_callback'
>      , m_callback(callback)
>        ^~~~~~~~~~
> /<<PKGBUILDDIR>>/sources/src/parser/addressparser.cpp: In member function 'virtual bool citygml::AddressParser::parseElementEndTag(const citygml::NodeType::XMLNode&, const string&)':
> /<<PKGBUILDDIR>>/sources/src/parser/addressparser.cpp:91:9: error: 'm_callback' was not declared in this scope
>          m_callback(std::move(m_address));
>          ^~~~~~~~~~
> /<<PKGBUILDDIR>>/sources/src/parser/addressparser.cpp:91:9: note: suggested alternative: 'malloc'
>          m_callback(std::move(m_address));
>          ^~~~~~~~~~
>          malloc
> sources/CMakeFiles/citygml.dir/build.make:1217: recipe for target 'sources/CMakeFiles/citygml.dir/src/parser/addressparser.cpp.o' failed
> make[3]: *** [sources/CMakeFiles/citygml.dir/src/parser/addressparser.cpp.o] Error 1
> make[3]: Leaving directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
> CMakeFiles/Makefile2:120: recipe for target 'sources/CMakeFiles/citygml.dir/all' failed
> make[2]: *** [sources/CMakeFiles/citygml.dir/all] Error 2
> make[2]: Leaving directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
> Makefile:152: recipe for target 'all' failed
> make[1]: *** [all] Error 2
> make[1]: Leaving directory '/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu'
> dh_auto_build: make -j1 returned exit code 2
>       cd /<<PKGBUILDDIR>>
> debian/rules:16: recipe for target 'build' failed
> make: *** [build] Error 2
> dpkg-buildpackage: error: debian/rules build gave error exit status 2
> ```

**Comment by sebastic** [comment]
Full build log: [libcitygml_2.0-3_unstable_gcc7.txt](https://github.com/jklimke/libcitygml/files/742786/libcitygml_2.0-3_unstable_gcc7.txt)

**Comment by jklimke** [comment]
i just pushed a change since the functional header include was missing for the addresselement parser. Could you try compiling again ?

**Comment by sebastic** [comment]
I've included the changes from c644e9e462fca870fdc7d8f0d2cb3bc122233acc and that indeed fixes the build failure with GCC 7. Thanks!
