### ISSUE TITLE
IntBuildingInstallation not handled?

### ISSUE THREAD

**Issue by KimJuYoung93** [jklimke/libcitygml#44]
I have citygml files with 'IntBuildingInstallation' tag what is not in source.
IntBuildingInstallation is not in the source. IntBuildingInstallation not handeled?

                 <bldg:roomInstallation>
                        **<bldg:IntBuildingInstallation**
                            **gml:id="GML_da67e87f-1715-4cae-83dc-2380837c7b10">**
                            <gml:description>Badewanne von ArchiCAD 14</gml:description>
                            <gml:name>Bathtub</gml:name>
                            <bldg:function>1070</bldg:function>
                            <bldg:lod4Geometry>
                                <gml:MultiSurface>
                                    <gml:surfaceMember>
                                        <gml:Polygon gml:id="PolyID36629_959_379253_37763">
                                            <gml:exterior>
                                                <gml:LinearRing
                                                  gml:id="PolyID36629_959_379253_37763_0">
                                                  <gml:pos>458881.04 5438361.2 0 </gml:pos>
                                                  <gml:pos>458881.04 5438361.2 0.6 </gml:pos>
                                                  <gml:pos>458881.04 5438362.7 0.6 </gml:pos>
                                                  <gml:pos>458881.04 5438362.7 0 </gml:pos>
                                                  <gml:pos>458881.04 5438361.2 0 </gml:pos>
                                                </gml:LinearRing>

**Comment by jklimke** [comment]
i guess this element is not explicitly supported right now. It should be relatively easy to add. Feel free to create a pull request.

**Comment by KimJuYoung93** [comment]
Thank you for answer.
The Citygml document contains the following intBuildingInstallation tag.

[ Citygml document ]
 "objects within a building which (in contrast to furniture) cannot be moved, are represented by the class IntBuildingInstallation. In contrast to BuildingFurniture, IntBuildingInstallations are permanently attached to the building structure and cannot be moved...."

However, only the 'intBuildingInstallation' tag is not defined in the 'nodetype.h' source in github as shown below.

[ nodetype.h ]
// BoundarySurfaceType
NODETYPE( BLDG, WallSurface )
NODETYPE( BLDG, RoofSurface )
NODETYPE( BLDG, GroundSurface )
NODETYPE( BLDG, ClosureSurface )
NODETYPE( BLDG, FloorSurface )
NODETYPE( BLDG, InteriorWallSurface )
NODETYPE( BLDG, CeilingSurface )
NODETYPE( BLDG, OuterCeilingSurface )
NODETYPE( BLDG, OuterFloorSurface )
NODETYPE( BLDG, BuildingFurniture )
NODETYPE( BLDG, CityFurniture )
NODETYPE( BLDG, Address)
           ...
