### ISSUE TITLE
error during run 

### ISSUE THREAD

**Issue by prashar91** [jklimke/libcitygml#47]
hallo it shows this error when i run 
it shows this error
Parsing CityGML file C:\libcitygml\bin\tester.gml using libcitygml v.2.0.8...
ERROR [C:\Users\prasharr\Desktop\testing\libcitygml-master\sources\src\parser\geometryelementparser.cpp:75] Expected start tag of GeometryObject but got gml:multicurve at line 52, column 25 in file C:\libcitygml\bin\tester.gml
ERROR [C:\Users\prasharr\Desktop\testing\libcitygml-master\sources\src\parser\parserxercesc.cpp:300] Unexpected Exception occurred: Unexpected start tag found.

**Comment by jklimke** [comment]
please try again with the newest version. There was a pull request fixing the support for multicurve elements
