### ISSUE TITLE
ParserParams::minLOD / maxLOD seem to be unused

### ISSUE THREAD

**Issue by shehzan10** [jklimke/libcitygml#48]
As the heading suggests, I don't seen any references to the `ParserParams::minLOD` and `ParserParams::maxLOD` member variables. These seem to be dummy variables for now.
Is there any plan to support these options?

**Comment by jklimke** [comment]
Actually yes, this is a unused variable. It seems that this feature has not been reimplemented when the library was refactored/rewritten. Since there is currently no active development from our side, we don't plan to implement it in the near future, but feel free to issue a pull request.
