### ISSUE TITLE
Need some help building

### ISSUE THREAD

**Issue by TJaenichen** [jklimke/libcitygml#49]
Hi,

thanks for putting all your good work into this. I really would like to give this lib a try but I am not c++ guy. So I tried for over a day now to get this to build (and the dependencies). So far I think I got a valid binary for xerces-c but when I try to compile libcitygml I get about 1000 warnings and 24 errors. Hunting those down lead me no where.

Long story shourt... I've seen that this apparently builds with CI. Could you send me a compiled .dll for windows? I'd be more than happy to send some beer money your way :)

Thanks for considering und viele Grüße

Thorsten

**Comment by jklimke** [comment]
unfortunately i don't have a windows machine to build on. Maybe you could just paste your errors here and i could have a short look at it.

**Comment by TJaenichen** [comment]
No problem. I think I found a solution! Thanks for getting back to quickly.

**Comment by jklimke** [comment]
Congratulations ;-) Then i'll close this ticket for now
