### ISSUE TITLE
VS2010 does not run successfully. Does the project need the support of C++11?

### ISSUE THREAD

**Issue by LitterBrother960** [jklimke/libcitygml#54]

**Comment by jklimke** [comment]
Hi. When building the project using CMAKE the generated project should be usable / compileable in VS2010. Are there any particular errors ? The project itself uses C++11, but the necessary settings should be handled by CMake when creating the project.

**Comment by LitterBrother960** [comment]
It seems not caused by lack of C++11 support, because when I use VS2010 to compile it, the C4430 error still exists
![微信图片编辑_20190712092648](https://user-images.githubusercontent.com/38416221/61095847-b4100600-a487-11e9-857f-ab4a57d21564.jpg)
![微信图片编辑_20190712092823](https://user-images.githubusercontent.com/38416221/61095858-bb371400-a487-11e9-830e-8de35f07e2da.jpg)

**Comment by LitterBrother960** [comment]
Thanks for your reply. The problem has been solved. The Xerces parsing library I used is MSVC10.0 version, but your code need the support of C++11. VS2013 indeed supports C++11 , but doesn't match MSVC10.0.So I searched for xerces_windows_vc12 and finally found it. The problem then was solved.
     I suggest you upload the xerces lib you used to the repository.

**Comment by jklimke** [comment]
I will not add a particular plattform xerces to the repository. But i added a hint to the readme that states that the minimum xerces version is 3.1 and it has to be compiled with C++11 support.

I hope this will do to avoid these kind of problems. I am always recommending to use an uptodate development environment as Visual Studio 2010 is meanwhile nearly 10 years old.
